# Generated by Django 3.1.4 on 2022-01-23 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcomments',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
